import { moveCharacter } from '../world/movement.js';
import { applyDamage } from '../combat/combat.js';
import { bindPointerJoystick } from './joystick.js';
import { restoreSlice, storeSlice } from './slice-state.js';
const scenery=document.querySelector('#scenery'),actors=document.querySelector('#actors');
const scene=[['environment/vegetation/tree_broadleaf_mature_01.png',4,25,27,47,'back'],['environment/vegetation/tree_conifer_01.png',19,17,18,52,'back'],['environment/architecture/riverford_house_01.png',66,28,30,38,'back'],['environment/architecture/riverford_market_stall_01.png',55,42,18,24,''],['environment/vegetation/tree_broadleaf_ancient_01.png',-8,27,38,62,''],['environment/ruins/ruin_arch_01.png',75,35,19,39,''],['environment/infrastructure/stone_bridge_section_01.png',72,57,25,22,''],['environment/infrastructure/timber_fence_01.png',50,58,20,15,''],['props/wood_signpost_01.png',44,55,8,20,''],['props/barrel_01.png',61,58,6,11,''],['props/crate_01.png',66,59,6,10,''],['environment/rocks/boulder_moss_01.png',12,67,15,15,''],['environment/vegetation/fallen_log_01.png',3,73,20,14,''],['environment/vegetation/fern_cluster_01.png',21,72,13,15,''],['environment/vegetation/shrub_01.png',87,66,14,17,''],['environment/vegetation/wildflower_cluster_01.png',36,71,8,12,''],['environment/ruins/ruin_wall_01.png',82,48,17,21,'back']];
for(const [src,x,y,w,h,c] of scene){const el=new Image();el.src='.runtime/assets/'+src;el.alt='';el.className=`asset ${c}`;Object.assign(el.style,{left:x+'%',top:y+'%',width:w+'%',height:h+'%'});scenery.append(el)}
function actor(id,src,cls,x,z,alt,hp){const el=new Image();Object.assign(el,{id,src:'.runtime/assets/'+src,alt,className:'actor '+cls});actors.append(el);return {id,el,transform:{x,z,y:0,yaw:0},resources:{hp,max:{hp}},alive:true,velocity:{x:0,z:0,y:0}}}
const player=actor('player','characters/player_exploration_base_01.png','player',0,0,'Aren',140),dog=actor('dog','creatures/companion_dog_exploration_01.png','dog',-2,-1,'Aren’s companion',40),farmer=actor('farmer','characters/npc_farmer_exploration_01.png','npc',-6,7,'Farmer Elian',90),wolf=actor('wolf','creatures/dire_wolf_exploration_01.png','wolf',8,14,'Dire wolf',72);
const $=s=>document.querySelector(s),keys=new Set(),joystick=bindPointerJoystick($('#joystick'),$('#joystickKnob'));let inCombat=false,last=performance.now(),enemyTimer;
const screen=t=>({left:47+t.x*2.25-t.z*.45,top:68-t.z*1.35+t.x*.08}),distance=(a,b)=>Math.hypot(a.transform.x-b.transform.x,a.transform.z-b.transform.z);
function refresh(){for(const a of [player,dog,farmer,wolf]){const p=screen(a.transform);Object.assign(a.el.style,{left:p.left+'%',top:p.top+'%',zIndex:Math.round(25+p.top)})}$('#hpbar').style.width=100*player.resources.hp/player.resources.max.hp+'%';$('#php').textContent=player.resources.hp;$('#whp').textContent=wolf.resources.hp;const nearFarmer=distance(player,farmer)<3.5,nearWolf=wolf.alive&&distance(player,wolf)<4;$('#prompt').hidden=(!nearFarmer&&!nearWolf)||inCombat;$('#prompt span').textContent=nearFarmer?'E · Speak with Elian':'E · Confront the dire wolf'}
function interact(){if(inCombat)return;if(distance(player,farmer)<3.5){$('#dialogue').hidden=false;return}if(wolf.alive&&distance(player,wolf)<4)startCombat()}
function startCombat(){inCombat=true;$('#combat').hidden=false;enemyTimer=setInterval(()=>{if(!inCombat)return;const hit=applyDamage(player,9,'dire-wolf');$('#combatlog').textContent=hit.defeated?'Aren falls. The Verge restores him at dawn.':`The wolf strikes for ${hit.amount}.`;if(hit.defeated){clearInterval(enemyTimer);setTimeout(()=>{player.alive=true;player.resources.hp=player.resources.max.hp;Object.assign(player.transform,{x:0,z:0});endCombat()},1200)}refresh()},1700)}
function strike(power=18){if(!inCombat)return;const hit=applyDamage(wolf,power,'player');wolf.el.hidden=!wolf.alive;$('#combatlog').textContent=hit.defeated?'The wolf yields and retreats into Wildwood.':`Aren strikes for ${hit.amount}.`;if(hit.defeated){clearInterval(enemyTimer);setTimeout(endCombat,900)}refresh()}
function cast(){if(!inCombat)return;$('#manifestation').hidden=false;$('#combatlog').textContent='The Binding Aura roots through soil and living stone.';strike(30);setTimeout(()=>$('#manifestation').hidden=true,900)}
function endCombat(){inCombat=false;$('#combat').hidden=true;clearInterval(enemyTimer);refresh()}
function save(){storeSlice(localStorage,'veilbound.slice.save',player,[wolf]);$('#save').textContent='JOURNEY SAVED';setTimeout(()=>{$('#save').textContent='SAVE JOURNEY'},1200)}
const saved=localStorage.getItem('veilbound.slice.save');if(saved){restoreSlice(saved,player,[wolf]);wolf.el.hidden=!wolf.alive}
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='e'){$('#dialogue').hidden?interact():$('#dialogue').hidden=true}if(e.code==='Space')strike();if(e.key.toLowerCase()==='q')cast();if(e.key==='Escape'){$('#dialogue').hidden=true;endCombat()}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
$('#closeDialogue').onclick=()=>$('#dialogue').hidden=true;$('#attack').onclick=()=>strike();$('#cast').onclick=cast;$('#flee').onclick=endCombat;$('#save').onclick=save;
$('#touchInteract').onclick=interact;$('#touchAttack').onclick=()=>strike();$('#touchCast').onclick=cast;
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(!inCombat&&$('#dialogue').hidden){const keyboardX=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),keyboardY=(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0);const x=keyboardX||joystick.value.x,y=keyboardY||-joystick.value.y;moveCharacter(player,{x,y},dt,4);player.transform.x=Math.max(-15,Math.min(17,player.transform.x));player.transform.z=Math.max(-4,Math.min(19,player.transform.z));dog.transform.x+=(player.transform.x-1.7-dog.transform.x)*dt*2.5;dog.transform.z+=(player.transform.z+1-dog.transform.z)*dt*2.5}refresh();requestAnimationFrame(frame)}refresh();requestAnimationFrame(frame);
